version: 0.0
os: linux
hooks:
    BeforeBlockTraffic:
        - location: scripts/before_block_traffic.sh
    AfterBlockTraffic:
        - location: scripts/after_block_traffic.sh
    ApplicationStop:
        - location: scripts/application_stop.sh
    BeforeInstall:
        - location: scripts/before_install.sh
    AfterInstall:
        - location: scripts/after_install.sh
    ApplicationStart:
        - location: scripts/application_start.sh
    ValidateService:
        - location: scripts/validate_service.sh
    BeforeAllowTraffic:
        - location: scripts/before_allow_traffic.sh
    AfterAllowTraffic:
        - location: scripts/after_allow_traffic.sh
